### ISSUE TITLE
El repositorio solo tiene el comit  inicial

### ISSUE THREAD

**Issue by JeanCarlosDev17** [jortiz3109/maraton-workshop-validaciones#3]
Hola estaba repasando el workshop del sábado, lo desarrollado durante el espacio de las validaciones los cambios no subieron al repositorio solo el comit inicial

**Comment by jortiz3109** [comment]
Hola Jean Carlos... los cambios están en la rama develop, puesto que la rama main es una rama solo para código estable listo para producción.
